name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Js dependencies
        run: yarn

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Install Rust dependencies
        run: cargo install wasm-bindgen-cli --version 0.2.72

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: build app
        run: cargo make build

      - name: Install Netlify CLI
        if: github.ref == 'refs/heads/master'
        run: |
          yarn global add --unsafe-perm=true netlify-cli
          echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN -p --dir ./dist
